/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UI;

import Concretas.Administrativo;
import Concretas.CitaMedica;
import Concretas.Doctor;
import Concretas.Enfermeria;
import Concretas.Hospital;
import Concretas.Paciente;
import Abstractas.Cita;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author jackb
 */
public class PantallaCitasAdmin extends javax.swing.JFrame {
    
    
    private final Hospital hospital;
    private final Administrativo admin;
    private final  ArrayList <Abstractas.Cita> visibleCitas = new java.util.ArrayList<>();
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PantallaCitasAdmin.class.getName());
    /**
     * Creates new form PantallaCitasAdmin
     * @param hospital
     * @param admin
     */
    public PantallaCitasAdmin(Hospital hospital, Administrativo admin) {
        this.hospital = hospital;
        this.admin = admin;
        initComponents();
        setLocationRelativeTo(null);
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Gestión de Citas");

        jButton1.setText("Nueva Cita");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Editar Cita");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Cancelar Cita");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reagendar Cita");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Volver");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Fecha ", "Hora ", "Paciente ", "Profesional", "Estado", "Consultario"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(359, 359, 359)
                .addComponent(jButton5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jButton1)
                .addGap(97, 97, 97)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(94, 94, 94)
                .addComponent(jButton4)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(353, 353, 353))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 462, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(19, 19, 19)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
//nueva cita
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if (hospital.getListaPacientes().isEmpty() || hospital.getListaDoctores().isEmpty()) {
        JOptionPane.showMessageDialog(this, "No hay pacientes o doctores cargados.");
        return;
    }

    Paciente p = hospital.getListaPacientes().get(0); // cambiar por selector si querés
    Doctor d = hospital.getListaDoctores().get(0);    // cambiar por selector si querés

    CitaMedica cita = new CitaMedica(
        "—","—",
        java.time.LocalDate.now(),
        java.time.LocalTime.of(10,0), d, p, 1
    );
    cita.setEstado("Pendiente");

    // agregar directamente al gestor del doctor
    d.getGestorCitas().agregarCita(cita, admin);

    actualizarTabla();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    int row = jTable1.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila.");
        return;
    }
    Cita c = visibleCitas.get(row);
    c.setEstado("Atendida");
    actualizarTabla();
    }//GEN-LAST:event_jButton2ActionPerformed
//cancelar cita
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
    int row = jTable1.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila.");
        return;
    }
    Cita c = visibleCitas.get(row);
    c.setEstado("Cancelada");
    actualizarTabla();
    }//GEN-LAST:event_jButton3ActionPerformed
//reagendar cita
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    int row = jTable1.getSelectedRow();
    if (row < 0) {
        JOptionPane.showMessageDialog(this, "Seleccione una fila.");
        return;
    }
    Cita c = visibleCitas.get(row);
    c.setEstado("Reagendada");
    actualizarTabla();
    }//GEN-LAST:event_jButton4ActionPerformed
//volver
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    new PantallaInicioAdmin(admin , hospital ).setVisible(true);
    this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void actualizarTabla() {
    DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
    model.setRowCount(0);
    model.setColumnIdentifiers(new String[]{
        "Fecha","Hora","Paciente","Profesional","Estado","Consultorio"
    });

    visibleCitas.clear();

    // Todas las citas de doctores
    for (Doctor d : hospital.getListaDoctores()) {
        for (Cita c : d.getGestorCitas().getListaCitas()) {
            visibleCitas.add(c);
            model.addRow(new Object[]{
                c.getFecha(), c.getHora(),
                c.getPacienteAsignado().getNombre(),
                c.getProfesionalAsignado().getNombre(),
                c.getEstado(), "H" + c.getConsultorioAsignado()
            });
        }
    }

    // Todas las citas de enfermeros
    for (Enfermeria e : hospital.getListaEnfermero()) {
        for (Cita c : e.getGestorCitas().getListaCitas()) {
            visibleCitas.add(c);
            model.addRow(new Object[]{
                c.getFecha(), c.getHora(),
                c.getPacienteAsignado().getNombre(),
                c.getProfesionalAsignado().getNombre(),
                c.getEstado(), "H" + c.getConsultorioAsignado()
            });
        }
    }
}    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
